package be.technifutur.java2020.Labo1;

public enum ControlerType {
    MAIN,
     MAINCONTROLER, STAGE,
    STAGECREATIONCONTROLER, STAGEEDITCONTROLER, STAGESUPPRESSIONCONTROLER, STAGEPRICECONTROLER,
    STAGEPLANNINGDISPLAYCONTROLER, STAGEDISPLAYCONTROLER,
    ACTIVITY,
    ACTIVITYCONTROLER, ACTIVITYCREATIONCONTROLER, ACTIVITYMODIFCONTROLER, ACTIVITYSUPPRESSIONCONTROLER, ACTIVITYREGISTERCONTROLER,
    CONTRIBUTOR,
    CONTRIBUTORCONTROLER, CONTRIBUTORCREATIONCONTROLER, CONTRIBUTOREDITCONTROLER, CONTRIBUTORSUPPRESSIONCONTROLER
}
