package be.technifutur.java2020.Labo1;

public enum ControlerType {
    MAINCONTROLER,
    STAGECREATIONCONTROLER, STAGEMODIFCONTROLER, STAGESUPPRESSIONCONTROLER,
    ACTIVITYCONTROLER, ACTIVITYCREATIONCONTROLER, ACTIVITYMODIFCONTROLER, ACTIVITYSUPPRESSIONCONTROLER, ACTIVITYREGISTERCONTROLER,
    CONTRIBUTORCONTROLER, CONTRIBUTORCREATIONCONTROLER, CONTRIBUTOREDITCONTROLER, CONTRIBUTORSUPPRESSIONCONTROLER
}
